<!-- annotation is part of apidoc -->
<!-- is is interpreted by tools -->
<annotation> :==
	<type-annotation> |
	<access-annotation> |
	<param-annotation> |
	<return-annotation> |
	<assert-annotation>
